### ISSUE TITLE
Exercise -ms-autohiding-scrollbar

### ISSUE THREAD

**Issue by comp615** [aarongustafson/WindowsPWAScrollBars#1]
Right now `none` and `scroll` are used, but the `-ms-autohiding-scrollbar` (which I think corresponds to auto) does not seem to be exhibited.

Side-note: scroll is incorrectly listed as scrollbar in the docs: https://developer.mozilla.org/en-US/docs/Web/CSS/-ms-overflow-style

**Comment by aarongustafson** [comment]
Fixed in 3a1d6e9

**Comment by aarongustafson** [comment]
@comp615 I added a new test and cleaned up some CSS bugs. Based on my testing, tests 2, 3 & 4 all end up with a normal size scrollbar that fades away after a few seconds. Test 1 never shows a scrollbar, but remains scrollable.
